apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: todoui
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: todoui
      labels:
        app: todoui
    spec:
      containers:
      - name: todoui
        image: novatec/technologyconsulting-containerexcerciseapp-todoui:v0.1
        imagePullPolicy: Always
      restartPolicy: Always
