FROM openjdk:8-alpine
RUN mkdir -p /opt/todobackend
ARG buildVersion
WORKDIR /opt/todobackend
COPY todobackend/target/todobackend-${buildVersion}.jar /opt/todobackend/todobackend.jar
CMD ["java", "-jar", "todobackend.jar"]
