FROM novatec/technologyconsulting-containerexcerciseapp-todoui:v0.1
COPY inspectit-ocelot-agent-1.6.1.jar /opt/todoui
CMD ["java", "-javaagent:/opt/todoui/inspectit-ocelot-agent-1.6.1.jar", "-jar", "todoui-0.0.1-SNAPSHOT.jar"]
