FROM novatec/technologyconsulting-containerexcerciseapp-todobackend:v0.1
COPY inspectit-ocelot-agent-1.6.1.jar /opt/todobackend
CMD ["java", "-javaagent:/opt/todobackend/inspectit-ocelot-agent-1.6.1.jar", "-jar", "todobackend-0.0.1-SNAPSHOT.jar"]
