FROM novatec/technologyconsulting-containerexerciseapp-todoui:v0.3
COPY inspectit-ocelot-agent-1.6.1.jar /opt/todoui
CMD ["java", "-XX:+ExitOnOutOfMemoryError", "-javaagent:/opt/todoui/inspectit-ocelot-agent-1.6.1.jar", "-jar", "todoui-0.0.1-SNAPSHOT.jar"]
