apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb 
spec:
  serviceName: posgresdb
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
       - image: postgres
         name: postgresdb
         env:
         - name: POSTGRES_USER
           valueFrom:
             secretKeyRef:
               name: db-security
               key: db.user.name
         - name: POSTGRES_PASSWORD
           valueFrom:
             secretKeyRef:
               name: db-security
               key: db.user.password
         - name: POSTGRES_DB
           valueFrom:
             configMapKeyRef:
               name: postgres-config
               key: postgres.db.name 
         ports:
         - containerPort: 5432
           name: postgresdb
         volumeMounts:
           - name: data
             mountPath: /var/lib/postgresql/data
